require('dotenv').config()
const pool = require('./db')

async function runMigration() {
  const client = await pool.connect()
  console.log('\n🔧 Migración: cambiar id de compras a ingreso manual...\n')

  try {
    await client.query('BEGIN')

    // Cambiar de GENERATED ALWAYS a GENERATED BY DEFAULT
    // Esto permite insertar el ID manualmente desde el frontend
    console.log('▶ Cambiando id a GENERATED BY DEFAULT...')
    await client.query(`
      ALTER TABLE compras
        ALTER COLUMN id SET GENERATED BY DEFAULT
    `)
    console.log('  ✅ OK\n')

    await client.query('COMMIT')
    console.log('🎉 Migración completada. El id de compras ahora puede ingresarse manualmente.\n')
  } catch (err) {
    await client.query('ROLLBACK')
    console.error('❌ Error, rollback aplicado:', err.message)
    process.exit(1)
  } finally {
    client.release()
    await pool.end()
  }
}

runMigration()
