-- ============================================================
-- Modificar tabla usuarios: ID de 5 dígitos único y aleatorio
-- Ejecutar en Neon SQL Editor
-- ============================================================

-- 1. Cambiar de GENERATED ALWAYS a GENERATED BY DEFAULT
--    para que el trigger pueda sobreescribir el ID
ALTER TABLE usuarios
  ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Función que genera un ID de 5 dígitos único
CREATE OR REPLACE FUNCTION generar_id_5_digitos()
RETURNS TRIGGER AS $$
DECLARE
  nuevo_id INTEGER;
  intentos INTEGER := 0;
BEGIN
  LOOP
    -- Genera número aleatorio entre 10000 y 99999
    nuevo_id := floor(random() * 90000 + 10000)::INTEGER;
    intentos := intentos + 1;

    -- Verifica que no exista ya (incluyendo eliminados lógicamente)
    EXIT WHEN NOT EXISTS (
      SELECT 1 FROM usuarios WHERE id = nuevo_id
    );

    -- Seguridad: evitar loop infinito (muy improbable con 90000 opciones)
    IF intentos > 1000 THEN
      RAISE EXCEPTION 'No se pudo generar un ID único después de 1000 intentos';
    END IF;
  END LOOP;

  NEW.id := nuevo_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Trigger BEFORE INSERT para asignar el ID automáticamente
DROP TRIGGER IF EXISTS trigger_id_5_digitos ON usuarios;

CREATE TRIGGER trigger_id_5_digitos
  BEFORE INSERT ON usuarios
  FOR EACH ROW
  EXECUTE FUNCTION generar_id_5_digitos();

-- 4. Verificar que funciona (opcional)
-- INSERT INTO usuarios (nombre, correo, usuario, rol, contraseña)
-- VALUES ('Test', 'test@test.com', 'testuser', 'Cajero', 'hash')
-- RETURNING id;  --> Debería retornar un ID entre 10000 y 99999
